### ISSUE TITLE
Write Disabled from Discord to Revolt

### ISSUE THREAD

**Issue by whim-witch** [williamhorning/lightning#106]
Hi,

I think I've mentioned this issue in the Bolt Discord also, but I'm still having an issue with Bolt not bridging messages from Discord to Revolt. It works the other way around. I've adjusted settings/permissions and event gave Bolt admin permissions, but this doesn't seem to make a difference. The settings have stayed the same for days, so it's not a matter of the permissions being changed too quickly (I hope). 

This is the message I get when I check on the status of the bot:
<img width="679" height="317" alt="Image" src="https://github.com/user-attachments/assets/f098395e-6ade-4bef-b517-efef8600fa87" />

These are the permissions for the bot on Revolt:
<img width="858" height="866" alt="Image" src="https://github.com/user-attachments/assets/c29828a5-4751-40a9-945e-72023b21bd4b" />
<img width="756" height="902" alt="Image" src="https://github.com/user-attachments/assets/d62f150d-d2a1-4ee6-b85a-a07bffaa7528" />
<img width="702" height="222" alt="Image" src="https://github.com/user-attachments/assets/002ff52d-878e-4c34-a065-0c7c309fe6e5" />

These are the permissions for the bot on Discord:
<img width="595" height="903" alt="Image" src="https://github.com/user-attachments/assets/926a0b0c-0f38-4802-91ba-f14936e9a5cd" />
<img width="609" height="944" alt="Image" src="https://github.com/user-attachments/assets/d70d7227-1a28-472c-b8d8-83ee43bf81ed" />
<img width="623" height="947" alt="Image" src="https://github.com/user-attachments/assets/cc56508f-b6f2-4d4f-9cb6-e42cd8914f77" />
<img width="586" height="965" alt="Image" src="https://github.com/user-attachments/assets/a6b5d688-acfe-47f9-977c-60a5a469e2ca" />
<img width="605" height="948" alt="Image" src="https://github.com/user-attachments/assets/39c3400e-5b3b-4002-bd9c-723aaecfc5fa" />
<img width="610" height="958" alt="Image" src="https://github.com/user-attachments/assets/3e1aa1fa-28dd-478a-8f5f-798e51ff21bd" />
<img width="602" height="967" alt="Image" src="https://github.com/user-attachments/assets/47b87154-371a-4dd7-b48d-1f20f35d8f10" />
<img width="600" height="892" alt="Image" src="https://github.com/user-attachments/assets/1b3cff05-50d9-4aaa-a011-1d53f658e01a" />
<img width="599" height="953" alt="Image" src="https://github.com/user-attachments/assets/5a04e03b-927c-449c-818c-10fbd2a8474a" />
<img width="616" height="880" alt="Image" src="https://github.com/user-attachments/assets/6e88699b-62d4-4750-82fc-9300b5c44e02" />

The "Bolt" role is assigned to the bot on both platforms.
<img width="606" height="334" alt="Image" src="https://github.com/user-attachments/assets/5fda5af4-9d7a-4803-bcda-3107fa3f5c1a" />
<img width="764" height="454" alt="Image" src="https://github.com/user-attachments/assets/2022d8d5-f074-40fd-b321-1ecac99b2af1" />

Messages will come from Revolt to Discord, but not the other way around.
<img width="385" height="170" alt="Image" src="https://github.com/user-attachments/assets/fc477c2a-9d1e-45f6-a53d-5276930bb5ca" />
<img width="442" height="157" alt="Image" src="https://github.com/user-attachments/assets/2e318b49-bdd0-4345-8fdd-aced029c3f75" />

What would you recommend I try to get Bolt to work? I'm very excited about the possibility of using this, but I can't understand what I'm doing wrong for it not to be granting write permissions. I've also tried closing and reopening the bridge a few times and it hasn't made a difference.

Thank you in advance!

**Comment by williamhorning** [comment]
hi! sorry for taking a bit to respond, but, the bot doesn't check permissions for channels which are marked at write disabled. once you ensure that the bot has all the right permissions, you should be able to leave the bridge on the revolt end (like `!bolt bridge leave <id>`_ and then joining it again (same command as before but join instead of leave) and the bot should work fine. if not, please let me know!

**Comment by williamhorning** [comment]
this should be fixed in rc.1, which'll make its way to the production bot sometime tonight. if you try again sometime soon, it should hopefully let you leave and rejoin

**Comment by whim-witch** [comment]
Thanks! I was able to leave, but now I'm having the opposite issue where now I can't join.
<img width="635" height="211" alt="Image" src="https://github.com/user-attachments/assets/ff755a44-9a58-4a53-9c4d-2e35d10e0a2f" />
<img width="621" height="398" alt="Image" src="https://github.com/user-attachments/assets/ad5fac60-0ef8-4fe1-8e31-2354bb74abac" />

Do I need to do something else? I am using the same ID.

**Comment by williamhorning** [comment]
you need to give the bot the necessary permissions on the revolt side: ChangeNickname, ChangeAvatar, ReadMessageHistory, SendMessage, ManageMessages, SendEmbeds, UploadFiles, Masquerade

**Comment by whim-witch** [comment]
I tried creating a new bridge since it seems like the old one from 2 months ago before there were direct messages from the bot could be the problem. I was able to successfully leave the old bridge and create a new one. However, I am still having the same problems as before. The bot has all of the permissions you mentioned that I showed in my initial screenshots. I'm not sure what other permissions are needed in order for this to work on Revolt. ReadMessageHistory is also not a permission option on the Revolt end.
<img width="1080" height="774" alt="Image" src="https://github.com/user-attachments/assets/39618efa-47ac-4ca8-b9d9-4f2cd5563876" />
<img width="962" height="244" alt="Image" src="https://github.com/user-attachments/assets/714e8e67-1a99-4823-b8b8-ac5c6276bb99" />
<img width="1076" height="1086" alt="Image" src="https://github.com/user-attachments/assets/5d6febe4-d49f-467b-8270-8f165613aa5d" />
<img width="1210" height="634" alt="Image" src="https://github.com/user-attachments/assets/14aac038-bc6e-4d5d-9c90-0df6feec6d0d" />

**Comment by williamhorning** [comment]
when you create a bridge, the bot will automatically join it in that channel, you shouldn't run the join command in the same channel in which you ran the create command. as for the permissions issue, it seems like that may be a bug with how the bot handles the [revolt permissions flow](https://developers.revolt.chat/assets/api/Permission%20Hierarchy.svg), which may be fixed in the next release, which i may make sometime today or tomorrow, though i can setup the channel for you in the meantime if you could send me the bridge id somehow (but preferably not in this issue)
